ThePetResort.UI/Controllers/OtherController.cs
using System.Web.Mvc;


namespace ThePetResortLLC.UI.Controllers
{
    
    
    public class OtherController : Controller
    {
        
        public ActionResult Faq()
        {
            return View();
        }

        public ActionResult Services()
        {
            return View();
        }
        
    }
}

ThePetResort.UI/Controllers/ReservationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThePetResort.DAL;

namespace ThePetResort.UI.Controllers
{
    public class ReservationsController : Controller
    {
        private PetResortEntities db = new PetResortEntities();

        // GET: Reservations
        public ActionResult Index()
        {
            var reservations = db.Reservations.Include(r => r.Pet).Include(r => r.ResortLocation);
            return View(reservations.ToList());
        }

        // GET: Reservations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // GET: Reservations/Create
        public ActionResult Create()
        {
            ViewBag.PetID = new SelectList(db.Pets, "PetID", "Name");
            ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName");
            return View();
        }

        // POST: Reservations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReservationID,ResortLocationID,PetID,ReservationDate")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Reservations.Add(reservation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.PetID = new SelectList(db.Pets, "PetID", "Name", reservation.PetID);
            ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName", reservation.ResortLocationID);
            return View(reservation);
        }

        // GET: Reservations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            ViewBag.PetID = new SelectList(db.Pets, "PetID", "Name", reservation.PetID);
            ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName", reservation.ResortLocationID);
            return View(reservation);
        }

        // POST: Reservations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReservationID,ResortLocationID,PetID,ReservationDate")] Reservation reservation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PetID = new SelectList(db.Pets, "PetID", "Name", reservation.PetID);
            ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName", reservation.ResortLocationID);
            return View(reservation);
        }

        // GET: Reservations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Reservation reservation = db.Reservations.Find(id);
            if (reservation == null)
            {
                return HttpNotFound();
            }
            return View(reservation);
        }

        // POST: Reservations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Reservation reservation = db.Reservations.Find(id);
            db.Reservations.Remove(reservation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ThePetResort.UI/Views/Other/Faq.cshtml
@{
    ViewBag.Title = "About";
}


<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">About</li>
        </ol>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <img src="~/Content/img/dog-holding-banner-1.jpg" class="img-responsive" />
    </div>
</div>
<!-- /.row -->
<!-- Service Paragraphs -->
<div class="col-md-8">
    <h2 class="page-header">About us</h2>
    <p>Our state-of-the-art facilities feature 24,000 square-feet of indoor space and six acres to run and play. Staffed by caring pet care professionals, Petopia offers exceptional boarding accommodations combined with a full range of canine and feline activities tailored to fit the unique needs and interests of each guest.
        Our friendly and knowledgeable staff provides full-service amenities including day camp, swimming in our indoor pool, bathing and grooming services, massage therapy, and all levels of training – sending pets home relaxed and happy after time well spent.
        We host free social events designed to be as much fun for you as much as they are for your pet. Please don’t miss our events page to save the date and join us.
        Personal tours during our business hours are encouraged to see the facility and see what all the cats and dogs are raving about!</p>
</div>
<div class="row">
    <div class="col-lg-12">
        <img src="~/Content/img/facilities.jpg" class="img-responsive" />
    </div>
</div>

<hr/>

<div>
    <div class="container">
        <h3>Our Facilities</h3>
        <div class="text-center">
            <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                <img src="~/Content/img/daycare/catdaycare3.jpg" alt="Susan" height="300px" width="350px">
                <h4>Susan</h4>
                <p>Cats love to climb, and this areas was built with that in mind. Here cats can find the perfect stoop to stretch and relax.</p>
            </div>
            <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                <img src="~/Content/img/daycare/daycare3.jpg" alt="Heather" height="300px" width="350px">
                <h4>Dog Play Area</h4>
                <p>Dogs are free to climb and play in the wading pool in a safe sanitary area</p>
            </div>
            <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms">
                <img src="~/Content/img/daycare/catdaycare2.png" alt="Danessa" height="300px" width="350px">
                <h4>Cat Sleeping Area</h4>
                <p>A wonderful place for cats to relax and find some much needed sleep</p>
            </div>
        </div>
    </div>
</div>

<hr/>

<div>
    <div class="container">
        <h3>Our Team</h3>	
        <div class="text-center">
            <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="300ms">
                <img src="~/Content/img/employees/rebekah.jpg" alt="Susan" height="300px" width="350px">
                <h4>Susan</h4>
                <p>Susan has been in the animal industry for over 20 years and brings a diverse background to Petopia. She has been fortunate to work in all different fields of animal care. From vet clinics and boarding facilities all the way to zoos and aquariums, she even owned her own successful pet sitting business for 11 years! Wanting to move to a warmer climate, she fell in love with Kansas City and moved down here from Connecticut. She has 2 dogs, Zeus’s Kausin’ Khaos a.k.a. “Khaos,” and Boot Scootin’ Boogey a.k.a. “Bootsie,” and three kitties, Simba, Nala, and Nubblestillskin a.k.a. “Nubins.”</p>
            </div>
            <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="600ms">
                <img src="~/Content/img/employees/heather.jpg" alt="Heather" height="300px" width="350px">
                <h4>Sara</h4>
                <p>Sara was born in Kansas City, but raised in West Virginia and Indiana. Sara’s family always had lots of pets and animals at home and that is where she developed her love for animals. She had always hoped to work with animals in some way, and found that professional grooming allowed her to be around animals and develop relationships with them and their owners. Sara loves what she does and believes grooming is an essential part of a pet’s well being. She loves the satisfaction of seeing pampered pooches flaunt their new ‘do for their parents!</p>
            </div>
            <div class="col-md-4 wow fadeInDown" data-wow-duration="1000ms" data-wow-delay="900ms">
                <img src="~/Content/img/employees/linda.jpg" alt="Danessa" height="300px" width="350px">
                <h4>Danessa</h4>
                <p>Denessa was born in sunny California but moved to Missouri at a young age. Her appreciation for animals stemmed from growing up with chickens and sheep. Denessa originally had plans to become a veterinarian, but she caught the grooming bug! She loves her job and looks forward to grooming the fur babies at The Belmont. Denessa spends her time outside grooming with her sweet daughter, Serenity.</p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">FAQ</h2>
    </div>
    <div class="col-lg-12">
        <div id="accordion" class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#collapseOne" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                            Do you have a minimum age requirement?
                        </a>
                    </h4>
                </div>
                <div class="panel-collapse collapse" id="collapseOne" style="height: 0;">
                    <div class="panel-body">
                        Yes. We require that puppies be at least 16 weeks old before coming to the facility. They must have had their rabies and be on their third round of puppy boosters. Cats must be 6 months old and also have their 3 month shots. Other animals may have specific requirments not listed.
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#collapseTwo" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                            What should I bring with my pet when boarding?
                        </a>
                    </h4>
                </div>
                <div class="panel-collapse collapse" id="collapseTwo" style="height: 0;">
                    <div class="panel-body">
                        We provide the bedding, bowls and entertainment. The only thing the owner is responsible for bringing is the food. We ask that the food be put in individual bags portioned for each meal so there is no confusion with the amount given. Toys and personal belongings are allowed. We are not responsible for any items that are lost or damaged throughout the stay.
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#collapseThree" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                            Since daycare is closed on weekends, does my dog still get playtime? 
                        </a>
                    </h4>
                </div>
                <div class="panel-collapse collapse" id="collapseThree">
                    <div class="panel-body">
                        Yes. On the weekends we are closed for daycare Drop Offs and Pick Ups, but the boarding dogs still get playtime.
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#collapseFour" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                            Do you offer boarding for other pets besides dogs and cats?
                        </a>
                    </h4>
                </div>
                <div class="panel-collapse collapse" id="collapseFour">
                    <div class="panel-body">
                        Yes! Species will vary by facility. Call us to inquire about your pet.
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#collapseFive" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                            Why does my pet need to be picked up by 6:00pm if you close at 7:00pm?
                        </a>
                    </h4>
                </div>
                <div class="panel-collapse collapse" id="collapseFive">
                    <div class="panel-body">
                        Even though we close at 7:00pm, our daycare section of the resort closes at 6:00pm. From 6:00pm - 7:00pm the staff is strictly here to clean the facility and to take care of the pets who are boarding that night. We take them outside to play, feed them dinner, and straighten up their suites for the night time.
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#collapseSix" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                            Do you have any breed restrictions? 
                        </a>
                    </h4>
                </div>
                <div class="panel-collapse collapse" id="collapseSix">
                    <div class="panel-body">
                        No. We believe that each dog is an individual and should be given a fair chance by going through a temperament test. With that being said, we are aware that some dogs may have a style of play that is not always suitable for the daycare environment. Many daycares ban all bully breeds, regardless of individual temperament. We do not feel a ban is necessary but we do take precautions. To be accepted into daycare, bully breeds must show good self-control, not be rude or space invasive to people, and have good knowledge of the following commands; sit, leave it, and come in addition to the regular requirements. Bully breeds tend to become quickly over-stimulated and escalate situations. For this reason, they will be allowed to play for short periods of time followed by rest periods that allow their arousal level to decrease.
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#collapseSeven" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                            Do you offer Daycare on weekends? 
                        </a>
                    </h4>
                </div>
                <div class="panel-collapse collapse" id="collapseSeven">
                    <div class="panel-body">
                        We do not. We are open on weekends only for boarding check ins and check outs. The dogs that are boarding get group playtime for the weekends, but the Daycare is closed.
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a href="#collapseEight" data-parent="#accordion" data-toggle="collapse" class="accordion-toggle collapsed">
                            Will my pet get sick by being around so many other dogs? 
                        </a>
                    </h4>
                </div>
                <div class="panel-collapse collapse" id="collapseEight">
                    <div class="panel-body">
                        We try to stay on top of any possible illness and take necessary precautions. However, just like with kids at school or daycare, viruses may be passed between pets. If your pet comes down with anything contagious, he/she must stay home until your vet says it’s okay to return.
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

ThePetResort.UI/Views/Other/Services.cshtml
@{
	ViewBag.Title = "Services";
}

<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<ol class="breadcrumb">
				<li>
					@Html.ActionLink("Home", "Index", "Home")
				</li>
				<li class="active">Services</li>
			</ol>
		</div>
	</div>
	<!-- /.row -->
	<div class="row">
		<div class="col-lg-12">
			<img src="~/Content/img/swimming_dogs.jpg" class="img-responsive" />
		</div>
	</div>
	<!-- /.row -->
	
	<div class="services" style="margin-left: -70px">
		<div class="container">
			<h3>Petopia Services</h3>
			<hr>
		    <div class="col-md-6">
		        <img src="~/Content/img/daycare/daycare1.jpg" class="img-responsive">
		        <p>Going on vacation? Why not treat your dog to one as well? Our friendly and attentive team will do everything we can to ensure Petopia feels like a home away from home to your pup. Whether they need overnight, weekend, holiday or extended care, your pet will spend their days enjoying supervised open play with their BFFFs (best furry friends forever), and their nights enjoying restful sleep.</p>
		    </div>

		    <div class="col-md-6" >
		        <div class="media">
		            <ul>
		                <li>
		                    <div class="media-left">
		                        <i class="fa fa-eye"></i>						
		                    </div>
		                    <div class="media-body">
		                        <h4 class="media-heading">SUPERVISED PLAYROOMS</h4>
		                        <p>Our playrooms are grouped by size, personality and play style to make sure your pet is safe and comfortable.</p>
		                    </div>
		                </li>
		                <li>
		                    <div class="media-left">
		                        <i class="fa fa-shield"></i>						
		                    </div>
		                    <div class="media-body">
		                        <h4 class="media-heading">A TEAM YOU CAN TRUST</h4>
		                        <p>As Petopians, we’re a unique breed. Our team of dog care professionals provide a safe and fully supervised environment.</p>
		                    </div>
		                </li>
		                <li>
		                    <div class="media-left">
		                        <i class="fa fa-users"></i>						
		                    </div>
		                    <div class="media-body">
		                        <h4 class="media-heading">SOCIALIZATION</h4>
		                        <p>Team members must complete rigorous training on dog body language and behavior.</p>
		                    </div>
		                </li>
		            </ul>
		        </div>
		    </div>
		</div>
    </div>
	
<div class="services" style="margin-left: -80px">
    <div class="container">
        <div class="col-md-6">
            <div class="media">
                <ul>
                    <li>
                        <div class="media-left">
                            <i class="fa fa-heart"></i>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">EXERCISE</h4>
                            <p>Pets boarded with us will burn off any excess energy during a full day of play. They will be tired but happy when they go to bed. </p>
                        </div>
                    </li>
                    <li>
                        <div class="media-left">
                            <i class="fa fa-cutlery"></i>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">DIET</h4>
                            <p>We also encourage you to bring your dog’s own food and treats. We’ll accommodate any special dietary needs your pup may have, and won’t charge extra for feeding or administering medication</p>
                        </div>
                    </li>
                    <li>
                        <div class="media-left">
                            <i class="fa fa-group"></i>
                        </div>
                        <div class="media-body">
                            <h4 class="media-heading">FAMILY</h4>
                            <p>We’ll make sure your pet feels happy, safe and fulfilled even when you can’t be with them. Petopia will be their home away from home where they’ll enjoy their own personal space to dream big and stay happy.</p>
                        </div>
                    </li>
                </ul>
            </div>
        </div>

        <div class="col-md-6">
            <img src="~/Content/img/daycare/catdaycare1.jpg" class="img-responsive">
            <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus interdum erat
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque
                libero, pulvinar tincidunt leo consectetur eget. Curabitur lacinia pellentesque</p>
        </div>
    </div>
</div>
    </div>
	
	
	
	

	<!-- Service Paragraphs -->
	<div class="row">
		<div class="col-md-8">
			<h2 class="page-header">Information and Requirements</h2>
				<p>Treat your pup or pups to a day full of play and fun at Petopia! We offer you a chance to give your special companion a safe and eventful day with well-qualified staff that will be there to give your pet the specialized attention he or she deserves!</p>
				<p>Our daycare areas are the only one of their kind in Kansas City. On the warm and sunny days, the dogs play in our fenced and closely monitored play area. On the not-so-warm-and-sunny days, the dogs get to come inside and play in one of our four indoor playrooms! All four indoor playrooms are climate controlled and specifically designed to remain clean and safe.</p>
				<p>We want to make sure that all of our pets enter a safe and happy environment. That being said, we require all pets to be currently vaccinated, neutered or spayed at the age of six months, and must complete a two part Temperament Test 48 hrs before any daycare reservations can be made.</p>
				<p>Although dog daycare is fantastic for well-socialized dogs and cats, it is not for everyone! Older pets, pets with health issues, or pets with an aggressive history might not be suitable for the daycare environment.
			</p>
		</div>
		<div class="col-md-4">
			<h2 class="page-header">Reservations</h2>
			<p>While we at Petopia always try to accommodate every family friend that shows up on our door step, some facilities have a max limit so that we can provide the very best care.</p>
			<p>
				Ready to make an reservation?
			</p>
			<a href="@Url.Action("Index", "Reservations")" class="btn btn-primary">Click Here!</a>
		</div>
	</div>
	<!-- /.row -->