ThePetResort.UI/Models/ContactViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ThePetResort.UI.Models
{
    public class ContactViewModel
    {
        [Required(ErrorMessage ="* Required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "* Required")]
        [RegularExpression(@"^[A-Za-z0-9](([_\.\-]?[a-zA-Z0-9]+)*)@([A-Za-z0-9]+)(([\.\-]?[a-zA-Z0-9]+)*)\.([A-Za-z]{2,})$", ErrorMessage = "Please enter a valid Email address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "* Required")]
        public string Subject { get; set; }

        [Required(ErrorMessage = "* Required")]
        public string Message { get; set; }
    }
}

ThePetResort.UI/Controllers/HomeController.cs
using System.Net;
using System.Net.Mail;
using System.Web.Mvc;
using ThePetResort.UI.Models;

namespace ThePetResort.UI.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Contact()
        {
            // Returns the contact form
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Contact(ContactViewModel contact)
        {
            // Create the body for the email

            // This assembles the message using the traditional string.Format method
            // var body = string.Format("Name: {0}<br/>Email: {1}<br/>Subject: {2}<br/>Message: {3}", contact.Name, contact.Email, contact.Subject, contact.Message);

            // We can also create the message using the new string interpolation method
            var body = string.Format($"Name: {contact.Name}<br/>Email: {contact.Email}<br/>Subject: {contact.Subject}<br/>Message: {contact.Message}");

            // We need to address our letter
            // We create and configure the Mail Message object
            MailMessage msg = new MailMessage(
                "no-reply@jameslcarter.com", // From address (this MUST be an email on your hosting account)
                "jlcarter.2342@gmail.com", // To address
                contact.Subject, // Subject from the user
                body // message of the email from the user
            );

            // Configure the Mail Message object
            msg.IsBodyHtml = true;
            // msg.CC.Add("dduderstadt@centriq.com"); // Carbon Copy another email address

            // msg.BCC.Add("email@domain.com"); // Adds a blind carbon copy
            msg.Priority = MailPriority.High;

            // Create and configure the SMTP client
            // aka building the post office
            SmtpClient client = new SmtpClient("mail.jameslcarter.com");
            client.Credentials = new NetworkCredential("no-reply@jameslcarter.com", "Donth@ckany1");

            // send the email
            using (client)
            {
                try
                {
                    client.Send(msg);
                }
                catch
                {
                    ViewBag.ErrorMessage = "There was an error sending your email. Please try again.";
                    return View();
                }
            }

            // Send them to the contact confirmation view and pass through
            // the contact information object (contact) to use that
            // information on the confirmation view
            return View("ContactConfirmation", contact);
        }

        public ActionResult Admin()
        {
            return View();
        }
    }
}

ThePetResort.UI/Controllers/OtherController.cs
using System.Web.Mvc;


namespace ThePetResortLLC.UI.Controllers
{
    
    
    public class OtherController : Controller
    {
        
        public ActionResult Faq()
        {
            return View();
        }

        public ActionResult Services()
        {
            return View();
        }
        
    }
}

ThePetResort.UI/Controllers/ReservationLimitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThePetResort.DAL;

namespace ThePetResort.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ReservationLimitsController : Controller
    {
        private PetResortEntities db = new PetResortEntities();

        // GET: ReservationLimits
        public ActionResult Index()
        {
            var reservationLimits = db.ReservationLimits.Include(r => r.ResortLocation).Include(r => r.Type);
            return View(reservationLimits.ToList());
        }

        // GET: ReservationLimits/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReservationLimit reservationLimit = db.ReservationLimits.Find(id);
            if (reservationLimit == null)
            {
                return HttpNotFound();
            }
            return View(reservationLimit);
        }

        // GET: ReservationLimits/Create
        public ActionResult Create()
        {
            ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName");
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "Name");
            return View();
        }

        // POST: ReservationLimits/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReservationLimitID,ResortLocationID,TypeID,Limit")] ReservationLimit reservationLimit)
        {
            if (ModelState.IsValid)
            {
                db.ReservationLimits.Add(reservationLimit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName", reservationLimit.ResortLocationID);
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "Name", reservationLimit.TypeID);
            return View(reservationLimit);
        }

        // GET: ReservationLimits/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReservationLimit reservationLimit = db.ReservationLimits.Find(id);
            if (reservationLimit == null)
            {
                return HttpNotFound();
            }
            ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName", reservationLimit.ResortLocationID);
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "Name", reservationLimit.TypeID);
            return View(reservationLimit);
        }

        // POST: ReservationLimits/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReservationLimitID,ResortLocationID,TypeID,Limit")] ReservationLimit reservationLimit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(reservationLimit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ResortLocationID = new SelectList(db.ResortLocations, "ResortLocationID", "ResortName", reservationLimit.ResortLocationID);
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "Name", reservationLimit.TypeID);
            return View(reservationLimit);
        }

        // GET: ReservationLimits/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ReservationLimit reservationLimit = db.ReservationLimits.Find(id);
            if (reservationLimit == null)
            {
                return HttpNotFound();
            }
            return View(reservationLimit);
        }

        // POST: ReservationLimits/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ReservationLimit reservationLimit = db.ReservationLimits.Find(id);
            db.ReservationLimits.Remove(reservationLimit);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ThePetResort.UI/Controllers/ResortLocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThePetResort.DAL;

namespace ThePetResort.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ResortLocationsController : Controller
    {
        private PetResortEntities db = new PetResortEntities();

        // GET: ResortLocations
        public ActionResult Index()
        {
            return View(db.ResortLocations.ToList());
        }

        // GET: ResortLocations/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResortLocation resortLocation = db.ResortLocations.Find(id);
            if (resortLocation == null)
            {
                return HttpNotFound();
            }
            return View(resortLocation);
        }

        // GET: ResortLocations/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ResortLocations/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ResortLocationID,ResortName,Address,City,State,ZipCode,Phone")] ResortLocation resortLocation)
        {
            if (ModelState.IsValid)
            {
                db.ResortLocations.Add(resortLocation);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(resortLocation);
        }

        // GET: ResortLocations/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResortLocation resortLocation = db.ResortLocations.Find(id);
            if (resortLocation == null)
            {
                return HttpNotFound();
            }
            return View(resortLocation);
        }

        // POST: ResortLocations/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ResortLocationID,ResortName,Address,City,State,ZipCode,Phone")] ResortLocation resortLocation)
        {
            if (ModelState.IsValid)
            {
                db.Entry(resortLocation).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(resortLocation);
        }

        // GET: ResortLocations/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ResortLocation resortLocation = db.ResortLocations.Find(id);
            if (resortLocation == null)
            {
                return HttpNotFound();
            }
            return View(resortLocation);
        }

        // POST: ResortLocations/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            ResortLocation resortLocation = db.ResortLocations.Find(id);
            db.ResortLocations.Remove(resortLocation);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ThePetResort.UI/Controllers/TypesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ThePetResort.DAL;
using Type = ThePetResort.DAL.Type;

namespace ThePetResort.UI.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TypesController : Controller
    {
        private PetResortEntities db = new PetResortEntities();

        // GET: Types
        public ActionResult Index()
        {
            return View(db.Types.ToList());
        }

        // GET: Types/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Type type = db.Types.Find(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            return View(type);
        }

        // GET: Types/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Types/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "TypeID,Name,IsExotic")] Type type)
        {
            if (ModelState.IsValid)
            {
                db.Types.Add(type);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(type);
        }

        // GET: Types/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Type type = db.Types.Find(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            return View(type);
        }

        // POST: Types/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "TypeID,Name,IsExotic")] Type type)
        {
            if (ModelState.IsValid)
            {
                db.Entry(type).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(type);
        }

        // GET: Types/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Type type = db.Types.Find(id);
            if (type == null)
            {
                return HttpNotFound();
            }
            return View(type);
        }

        // POST: Types/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Type type = db.Types.Find(id);
            db.Types.Remove(type);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ThePetResort.UI/Views/Home/Admin.cshtml
@{
    ViewBag.Title = "Admin";
}

<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Admin</li>
        </ol>
    </div>
</div>

<div class="container" style="margin-left: -15px">
    <div class="col-md-4">
        <img src="~/Content/img/Admin/map.png" alt="map" height="300px" width="350px">
        <h2 class="page-header">Resort Locations</h2>
        <p>Create, Edit, Delete, or view Details of all the resort locations</p>
        <a href="@Url.Action("Index", "ResortLocations")" class="btn btn-primary">Click Here</a>
    </div>

    <div class="col-md-4">
        <img src="~/Content/img/Admin/limit.jpg" alt="map" height="300px" width="350px">
        <h2 class="page-header">Limits</h2>
        <p>Create, Edit, Delete, or view Details of each resort's limit</p>
        <a href="@Url.Action("Index", "ReservationLimits")" class="btn btn-primary">Click Here!</a>
    </div>

    <div class="col-md-4">
        <img src="~/Content/img/Admin/roles.jpg" alt="map" height="300px" width="350px">
        <h2 class="page-header">Roles</h2>
        <p>Create, Edit, Delete, or view Details of the site specific roles</p>
        <a href="@Url.Action("Index", "RolesAdmin")" class="btn btn-primary">Click Here!</a>
    </div>

    
    <div class="col-md-4" style="margin-top: 20px">
        <img src="~/Content/img/Admin/customer.jpg" alt="map" height="300px" width="350px">

        <h2 class="page-header">Users</h2>
        <p>Create, Edit, Delete, or view Details of all site users</p>
        <a href="@Url.Action("Index", "UsersAdmin")" class="btn btn-primary">Click Here!</a>
    </div>
    
    <div class="col-md-4" style="margin-top: 20px">
        <img src="~/Content/img/Admin/meerkat.jpg" alt="map" height="300px" width="350px">

        <h2 class="page-header">Types</h2>

        <p>Create, Edit, Delete, or view Details of all breeds and species</p>
        <a href="@Url.Action("Index", "Types")" class="btn btn-primary">Click Here!</a>
    </div>
</div>

ThePetResort.UI/Views/Home/Contact.cshtml
@model ThePetResort.UI.Models.ContactViewModel
@{
	ViewBag.Title = "Contact | cStore";
}

<div class="row">
	<div class="col-lg-12">
		<ol class="breadcrumb">
			<li>@Html.ActionLink("Home", "Index", "Home")</li>
			<li class="active">Contact</li>
		</ol>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<img src="~/Content/img/kitten_on_grass.jpg" class="img-responsive" />
	</div>
</div>


<div class="row">
			<div class="col-sm-8">
				<div class="contact-form">
					<h2 class="title text-center">Get In Touch</h2>
					<div class="status alert alert-success" style="display: none"></div>
					@using (Html.BeginForm("Contact", "Home", FormMethod.Post, new { id = "main-contact-form", @class = "contact-form row" }))
					{
						@Html.AntiForgeryToken()
						<div class="form-group col-md-6">
							<input type="text" name="name" class="form-control" placeholder="Name">
							<span id="nameVal" class="invalid"></span>
						</div>
						<div class="form-group col-md-6">
							<input type="text" name="email" class="form-control" placeholder="Email">
							<span id="emailVal" class="invalid"></span>
						</div>
						<div class="form-group col-md-12">
							<input type="text" name="subject" class="form-control" placeholder="Subject">
							<span id="subjectVal" class="invalid"></span>
						</div>
						<div class="form-group col-md-12">
							<textarea name="message" id="message" class="form-control" rows="8" placeholder="Your Message Here"></textarea>
							<span id="messageVal" class="invalid"></span>
						</div>
						<div class="form-group col-md-12">
							<input type="submit" name="submit" class="btn btn-primary pull-right" value="Submit">
						</div>
					}
				</div>
			</div>
			<div class="col-sm-4">
				<div class="contact-info">
					<h1></h1><h2></h2>
					<h2 class="title text-center">Contact Info</h2>

					<address>
						<p>Petopia</p>
						<p>1578 Woodhill Drive</p>
						<p>Blue Springs, MO 64133</p>
						<p>Phone: 816-555-5555</p>
						<p>Email: info@thepetresort.com</p>
						<hr/>
						<p>Hours</p>
						<p>Monday: 6:00 A.M. - 7:00 P.M.</p>
						<p>Tuesday: 6:00 A.M. - 7:00 P.M.</p>
						<p>Wednesday: 6:00 A.M. - 7:00 P.M.</p>
						<p>Thursday: 6:00 A.M. - 7:00 P.M.</p>
						<p>Friday: 6:00 A.M. - 7:00 P.M.</p>
						<p>Saturday: Weekend boarding only</p>
						<p>Sunday: Weekend boarding only</p>
					</address>
				</div>
			</div>
		</div>
@*/#contact-page*@
	

ThePetResort.UI/Views/Home/ContactConfirmation.cshtml
@model ThePetResort.UI.Models.ContactViewModel
@{
    ViewBag.Title = "ContactConfirmation";
}

<div id="contact-page" class="container">
    <div class="bg">
        <div class="row">
            <div class="col-sm-12">
                <div class="text-center alert alert-success">
                    Thank you for contacting us, @Model.Name! We will get back to you within 24 hours
                </div>
            </div>
        </div>
    </div>
</div><!--/#contact-page-->

ThePetResort.UI/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}



<div class="container">
    <br>
    <section id="main-slider" class="no-margin">
        <div class="carousel slide">
            <div class="carousel-inner">
                <div class="item active" style="background-image: url('../../Content/img/slider/slider.jpg');">
                    <div class="container">
                        <div class="row slide-margin">
                            <div class="col-sm-6">
                                <div class="carousel-content">
                                    <h2 class="animation animated-item-1" style="color:black"><span>PET</span>OPIA</h2>
                                    <p class="animation animated-item-2" style="color: black">When you want the best possible care and attention for your pet</p>
                                    <a class="btn-slide animation animated-item-3" href="@Url.Action("Services", "Other")">Read More</a>
                                </div>
                            </div>

                            <div class="col-sm-6 hidden-xs animation animated-item-4">
                                <div class="slider-img">
                                    <img src="~/Content/img/slider/Kitten.png" />
                                </div>
                            </div>

                        </div>
                    </div>
                </div><!--/.item-->
            </div><!--/.carousel-inner-->
        </div><!--/.carousel-->
    </section><!--/#main-slider-->
</div>

<hr/>

<div class="row">
    <div class="col-lg-12">
        
        <h2>More than a boarding room</h2>
        <p>There are times when boarding and daycare is just not enough. Petopia would not be complete without a relaxing spa for our very important four legged guests.Our guests can enjoy a relaxing massage, a luxurious brush and blowout, or even a full haircut with our fantastic furstylist - Sara Cox and Denessa Coats. The Six Senses offers everything from full grooming to a quick bath.

            Both our groomers specialize in the finest personalized hair cuts, styling, and blowouts that Nashville has to offer. Your pooch will enjoy the ultimate in five star luxury as they embark on their special Spa day experience! If you would like to make a grooming appointment, please call our concierge.</p>
        <img src="~/Content/img/Luxurybanner.jpg" class="img-responsive" />
    </div>
</div>

    

<!-- Service Images -->
<div class="row">
    <div class="col-lg-12">
        <h2 class="page-header">Services</h2>
    </div>
    <div class="col-sm-4">
        <img src="~/Content/img/running_dogs.jpg" class="img-responsive">
        <h3>Boarding</h3>
        <p>Boarding your pet at Petopia keeps them safe, happy, and comfortable. We offer short and long term packages, while guests at our Blue Springs Resort enjoy plenty of fresh air and room to play on our 6-acre site in the Grain Valley Corporate Center.</p>
    </div>
    <div class="col-sm-4">
        <img src="~/Content/img/pig.jpg" class="img-responsive">
        <h3>Daycare</h3>
        <p>Our day camp program at Petopia is the perfect, worry-free alternative to leaving your pet at home. Rain or shine, your pet will enjoy a day of fun, attention and companionship in a healthy, caring atmosphere.</p>
        <p>A typical day at Petopia includes 2 to 4 hours of morning and afternoon play, punctuated by a 2-hour nap and refreshment period at mid-day. </p>
    </div>
    <div class="col-sm-4">
        <img src="~/Content/img/animal_spa.jpg" class="img-responsive">
        <h3>Grooming & Spa</h3>
        <p>Treat your pet to a wonderful day at our amazing spa! Petopia's full-service salon offers everything your pet needs to go home feeling fresh, pampered, and looking great. We want all of our pets to look and feel their best.</p>
    </div>
</div>
<!-- /.row -->


<!-- jQuery -->
<script src="~/Content/js/jquery.js"></script>

<!-- Bootstrap Core JavaScript -->
<script src="~/Content/js/bootstrap.min.js"></script>

<!-- Script to Activate the Carousel -->
<script>
    $('.carousel').carousel({
        interval: 5000 //changes the speed
    })
</script>