ThePetResort.UI/Controllers/PetsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using cStoreMVC.UI.Exceptions;
using PetResort.UI.Services;
using ThePetResort.DAL;

namespace ThePetResort.UI.Controllers
{
    public class PetsController : Controller
    {
        private readonly PetResortEntities db = new PetResortEntities();

        // GET: Pets
        public ActionResult Index()
        {
            var pets = db.Pets.Include(p => p.Type);
            return View(pets.ToList());
        }

        // GET: Pets/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }
            return View(pet);
        }

        // GET: Pets/Create
        public ActionResult Create()
        {
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "Name");
            return View();
        }

        // POST: Pets/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PetID,Name,TypeID,PetPhoto,SpecialNotes,IsVIP,DateAdded")] Pet pet, HttpPostedFileBase PetPhoto)
        {
            if (ModelState.IsValid)
            {
                var imageName = "";

                var imgExt = Path.GetExtension(PetPhoto?.FileName);
                if (imgExt != null)
                {
                    imgExt = imgExt.ToLower();
                    string[] allowedExtensions = { ".png", ".jpg", ".jpeg", ".gif" };

                    if (allowedExtensions.Contains(imgExt))
                    {

                        imageName = Path.GetFileName(PetPhoto.FileName);

                        string savePath = Server.MapPath("~/Content/img/pets/");

                        Image convertedImage = Image.FromStream(PetPhoto.InputStream);

                        int maxImageSize = 500;

                        int maxThumbSize = 100;

                        ImageService.ResizeImage(savePath, imageName, convertedImage, maxImageSize, maxThumbSize);
                    }
                    else
                    {
                        throw new InvalidFileTypeException("Invalid file type. Only .png, .jpg, or .jpeg files allowed.");
                    }
                }

                pet.PetPhoto = imageName;

                db.Pets.Add(pet);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "Name", pet.TypeID);
            return View(pet);
        }

        // POST: Pets/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PetID,Name,TypeID,PetPhoto,SpecialNotes,IsVIP,DateAdded")] Pet pet)
        {
            if (ModelState.IsValid)
            {
                db.Entry(pet).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TypeID = new SelectList(db.Types, "TypeID", "Name", pet.TypeID);
            return View(pet);
        }

        // GET: Pets/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Pet pet = db.Pets.Find(id);
            if (pet == null)
            {
                return HttpNotFound();
            }
            return View(pet);
        }

        // POST: Pets/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Pet pet = db.Pets.Find(id);
            db.Pets.Remove(pet);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ThePetResort.UI/Views/Pets/Create.cshtml
@model ThePetResort.DAL.Pet

@{
    ViewBag.Title = "Create";
}

<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Create</li>
        </ol>
    </div>
</div>


@using (Html.BeginForm("Create", "Pets", FormMethod.Post, new { enctype = "multipart/form-data" })) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeID, "TypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("TypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PetPhoto, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                <label>Upload Image:</label>
                <input type="file" name="PetPhoto" id="PetPhoto" />
                @Html.ValidationMessageFor(model => model.PetPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialNotes, new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
            </div>
        </div>

        @if (User.IsInRole("Admin, Employee"))
        {
        <div class="form-group">
            @Html.LabelFor(model => model.IsVIP, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                <div class="checkbox">
                    @Html.EditorFor(model => model.IsVIP)
                    @Html.ValidationMessageFor(model => model.IsVIP, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DateAdded, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.DateAdded, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DateAdded, "", new { @class = "text-danger" })
            </div>
        </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ThePetResort.UI/Views/Pets/Delete.cshtml
@model ThePetResort.DAL.Pet

@{
    ViewBag.Title = "Delete";
}

<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Delete</li>
        </ol>
    </div>
</div>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetPhoto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetPhoto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialNotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsVIP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsVIP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

ThePetResort.UI/Views/Pets/Details.cshtml
@model ThePetResort.DAL.Pet

@{
    ViewBag.Title = "Details";
}

<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Details</li>
        </ol>
    </div>
</div>

<div>
    <h4>Pet</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PetPhoto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PetPhoto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.SpecialNotes)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.SpecialNotes)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsVIP)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsVIP)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DateAdded)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DateAdded)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Type.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PetID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

ThePetResort.UI/Views/Pets/Edit.cshtml
@model ThePetResort.DAL.Pet

@{
    ViewBag.Title = "Edit";
}

<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Edit</li>
        </ol>
    </div>
</div>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Pet</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PetID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TypeID, "TypeID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.DropDownList("TypeID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TypeID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PetPhoto, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.PetPhoto, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PetPhoto, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.SpecialNotes, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-4">
                @Html.EditorFor(model => model.SpecialNotes, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.SpecialNotes, "", new { @class = "text-danger" })
            </div>
        </div>
        @if (User.IsInRole("Admin, Employee"))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.IsVIP, htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-4">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.IsVIP)
                        @Html.ValidationMessageFor(model => model.IsVIP, "", new {@class = "text-danger"})
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.DateAdded, htmlAttributes: new {@class = "control-label col-md-2"})
                <div class="col-md-4">
                    @Html.EditorFor(model => model.DateAdded, new {htmlAttributes = new {@class = "form-control"}})
                    @Html.ValidationMessageFor(model => model.DateAdded, "", new {@class = "text-danger"})
                </div>
            </div>
        }

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ThePetResort.UI/Views/Pets/Index.cshtml
@model IEnumerable<ThePetResort.DAL.Pet>

@{
    ViewBag.Title = "Index";
}

<div class="row">
    <div class="col-lg-12">
        <ol class="breadcrumb">
            <li>@Html.ActionLink("Home", "Index", "Home")</li>
            <li class="active">Pets</li>
        </ol>
    </div>
</div>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PetPhoto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.SpecialNotes)
        </th>
        @if (User.IsInRole("Admin, Employee"))
        {
            <th>
                @Html.DisplayNameFor(model => model.IsVIP)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateAdded)
            </th>
        }
        <th>
            @Html.DisplayNameFor(model => model.Type.Name)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PetPhoto)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.SpecialNotes)
        </td>
        @if (User.IsInRole("Admin, Employee"))
        {
            <td>
                @Html.DisplayFor(modelItem => item.IsVIP)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DateAdded)
            </td>
        }
        <td>
            @Html.DisplayFor(modelItem => item.Type.Name)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PetID }) |
            @Html.ActionLink("Details", "Details", new { id=item.PetID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PetID })
        </td>
    </tr>
}

</table>